Improve argument handling, help message.
pelias
	-Expand the help message significantly, documenting this tool's
	purpose and detailed usage.
	-Improve bad argument handling.

diff --git a/pelias b/pelias
--- a/pelias
+++ b/pelias
@@ -1,24 +1,44 @@
 #! /usr/bin/env bash
 
-help_message=$(cat << EOF
-usage: pelias --help | <subcommand> <script> [scriptArgs]
+help_message=$(cat << "EOF"
+usage: pelias --help | <subcommand>[#<tag>] <script> [scriptArgs]
+
+`pelias` is a lightweight tool that abstracts away all of the Pelias
+repositories behind one CLI, so that users no longer have to worry about
+cloning, installing, and generally dealing with multiple moving parts in
+different places (like the API, schema, and various importers). The tool
+accepts two parameters: the repository to target, and the script inside it to
+run. `pelias api start` will target the `start` script inside the
+`github.com/pelias/api` repository. The scripts are defined inside that
+repository's `package.json`'s `scripts` object; in other words, they're
+anything that can be executed via `npm run` inside that package.
+
+Repositories will be stored inside `~/.pelias/`. When one is invoked and isn't
+found locally, it'll be cloned and `npm install`'d; otherwise, the tool will
+check for upstream changes and pull them/reinstall in if necessary.
 
 	--help: Print this help message and exit.
-	<subcommand>: The name of the repository under github.com/pelias/ to
-		target.
-	<script>: The script defined inside the <subcommand> repo's
-		package.json to run.
+	<subcommand>: The name of the repository under github.com/pelias/ to target.
+	[<tag>]: A specific commit hash, branch name, or tag to `git checkout`
+		inside the <subcommand> repo.
+	<script>: The script defined inside the <subcommand> repo's package.json to run.
 	[args]: Any args to pass to <script>
 EOF
 )
 
+print_error(){
+	>&2 printf "Error: $1\n\n$help_message\n"
+}
+
 if [ -z "$1" ]; then
-	>&2 echo "Missing subcommand."
-	>&2 echo "$help_message"
+	print_error "Missing argument."
 	exit 1
 elif [ "$1" = "--help" ]; then
 	echo "$help_message"
 	exit 0
+elif [ -z "$2" ]; then
+	print_error "Missing subcommand."
+	exit 1
 else
 	IFS="#"
 	components=($1)
